// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemoteSSL.Infrastructure.Persistence;

#nullable disable

namespace RemoteSSL.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RemoteSslDbContext))]
    [Migration("20260814111506_F20DomainValidation")]
    partial class F20DomainValidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RemoteSSL.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BreakGlass")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CertificateRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("DeploymentJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CertificateVersionId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Ciphertext")
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("DeploymentJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PurgeReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sensitivity")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("WrappedDataKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CertificateVersionId");

                    b.HasIndex("DeploymentJobId");

                    b.HasIndex("ExpiresAt", "PurgedAt");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ApprovalReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NewFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OldFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("SealedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Actor");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Sequence");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CaConnectorConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EncryptedConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("CaConnectors");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CertificatePolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Environment")
                        .HasColumnType("text");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<Guid?>("RenewalPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CommonName");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificatePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowWildcard")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedDomainSuffixesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AllowedEcCurvesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BlockWeakSignatureAlgorithms")
                        .HasColumnType("boolean");

                    b.Property<string>("BlockedDomainSuffixesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnforceSeparationOfDuties")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxValidityDays")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumRsaBits")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RenewBeforeDays")
                        .HasColumnType("integer");

                    b.Property<string>("RequireApprovalInJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequireOwner")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequirePostDeploymentProbe")
                        .HasColumnType("boolean");

                    b.Property<string>("RequireWindowInJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RotateKeyOnRenewal")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WarnOnOverlap")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.ToTable("CertificatePolicies");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaConnectorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CsrPem")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedPrivateKeyPem")
                        .HasColumnType("text");

                    b.Property<string>("Environment")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("IssuedVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("KeyAlgorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyOrigin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeySizeOrCurve")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderRequestId")
                        .HasColumnType("text");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("text");

                    b.Property<string>("SansJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetKeyPath")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("CertificateRequests");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateSan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SanType")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("CertificateVersionId");

                    b.HasIndex("Value");

                    b.ToTable("CertificateSans");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StorePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("StoreType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.ToTable("CertificateStores");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaIssuerUrlsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CrlDistributionPointsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedPrivateKeyPem")
                        .HasColumnType("text");

                    b.Property<string>("ExtendedKeyUsagesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCertificateAuthority")
                        .HasColumnType("boolean");

                    b.Property<string>("IssuerDn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeySize")
                        .HasColumnType("integer");

                    b.Property<string>("KeyUsagesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OcspUrlsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PathLengthConstraint")
                        .HasColumnType("integer");

                    b.Property<string>("PemCertificate")
                        .HasColumnType("text");

                    b.Property<string>("PemChain")
                        .HasColumnType("text");

                    b.Property<string>("PublicKeyAlgorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Sha1Thumbprint")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Sha256Thumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SignatureAlgorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectDn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("NotAfter");

                    b.HasIndex("Sha256Thumbprint")
                        .IsUnique();

                    b.HasIndex("IssuerDn", "SerialNumber");

                    b.ToTable("CertificateVersions");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CredentialRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessPolicyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CredentialType")
                        .HasColumnType("integer");

                    b.Property<string>("EncryptedSecret")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastAccessedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LastRotatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<int>("RotationIntervalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("RotationPending")
                        .HasColumnType("boolean");

                    b.Property<string>("SecretIdentifier")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CredentialRefs");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationPolicyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateStoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceBindingJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("CertificateStoreId");

                    b.ToTable("DeploymentBindings");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("CertificateVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ManualContinuation")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("RolledBackFromJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("StopOnFailure")
                        .HasColumnType("boolean");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CertificateVersionId");

                    b.HasIndex("CorrelationId");

                    b.ToTable("DeploymentJobs");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJobTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeploymentBindingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeploymentJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentBindingId");

                    b.HasIndex("DeploymentJobId");

                    b.ToTable("DeploymentJobTargets");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeploymentJobTargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("SafeLog")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentJobTargetId");

                    b.ToTable("DeploymentSteps");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DomainValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaConnectorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChallengeReference")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ExpectedDnsRecord")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedHttpResponse")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CertificateRequestId");

                    b.ToTable("DomainValidations");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Key", "Endpoint")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.ManagedKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("DestroyedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedPrivateKeyPem")
                        .HasColumnType("text");

                    b.Property<string>("Environment")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Exportable")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OwnerTeam")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("PublicKeyPem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("SizeOrCurve")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Label");

                    b.ToTable("ManagedKeys");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.MetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ValueMs")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Metric", "Timestamp");

                    b.ToTable("MetricSamples");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.MonitorCertificateLink", b =>
                {
                    b.Property<Guid>("MonitorEndpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MonitorEndpointId", "CertificateId");

                    b.HasIndex("CertificateId");

                    b.ToTable("MonitorCertificateLinks");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.MonitorEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExternalProbeEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("HealthCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HealthCheckDetail")
                        .HasColumnType("text");

                    b.Property<int?>("HealthCheckExpectedStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("HealthCheckLatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("HealthCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HealthCheckUrl")
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("InternalChainError")
                        .HasColumnType("text");

                    b.Property<bool?>("InternalChainValid")
                        .HasColumnType("boolean");

                    b.Property<string>("InternalCipherSuite")
                        .HasColumnType("text");

                    b.Property<bool?>("InternalHostnameValid")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("InternalObservedVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("InternalProbeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalProbeError")
                        .HasColumnType("text");

                    b.Property<int>("InternalProbeStatus")
                        .HasColumnType("integer");

                    b.Property<string>("InternalTlsProtocol")
                        .HasColumnType("text");

                    b.Property<string>("LastChainError")
                        .HasColumnType("text");

                    b.Property<bool?>("LastChainValid")
                        .HasColumnType("boolean");

                    b.Property<string>("LastCipherSuite")
                        .HasColumnType("text");

                    b.Property<bool?>("LastHostnameValid")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastObservedVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastProbeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastProbeError")
                        .HasColumnType("text");

                    b.Property<int>("LastProbeStatus")
                        .HasColumnType("integer");

                    b.Property<string>("LastTlsProtocol")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int?>("ProbeIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sni")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InternalObservedVersionId");

                    b.HasIndex("LastObservedVersionId");

                    b.HasIndex("Host", "Port", "Sni")
                        .IsUnique();

                    b.ToTable("MonitorEndpoints");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeliveredChannelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt", "OccurredAt");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.RenewalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ApprovalRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoDeploy")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CaConnectorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MaintenanceWindowJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text");

                    b.Property<bool>("RotateKey")
                        .HasColumnType("boolean");

                    b.Property<int>("TriggerDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RenewalPolicies");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.RunnerCertificateAuthority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificatePem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedKeyPem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RunnerAuthorities");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.RunnerJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeploymentJobTargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "RunnerId");

                    b.ToTable("RunnerJobs");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.RunnerNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterVersionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiKeyHash")
                        .HasColumnType("text");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IdentityCertThumbprint")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("IdentityRevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityRevokedReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Segment")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Runners");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.ServicePath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MonitorIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ServicePaths");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConnectionConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CredentialRefId")
                        .HasColumnType("uuid");

                    b.Property<string>("Environment")
                        .HasColumnType("text");

                    b.Property<string>("HaRole")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OsType")
                        .HasColumnType("text");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetGroup")
                        .HasColumnType("text");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CredentialRefId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ExternalSubject")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateSan", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.CertificateVersion", "CertificateVersion")
                        .WithMany("Sans")
                        .HasForeignKey("CertificateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificateVersion");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateStore", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.Target", "Target")
                        .WithMany("Stores")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateVersion", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.Certificate", "Certificate")
                        .WithMany("Versions")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentBinding", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemoteSSL.Domain.Entities.CertificateStore", "CertificateStore")
                        .WithMany("Bindings")
                        .HasForeignKey("CertificateStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("CertificateStore");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJob", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.CertificateVersion", "CertificateVersion")
                        .WithMany()
                        .HasForeignKey("CertificateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificateVersion");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJobTarget", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.DeploymentBinding", "DeploymentBinding")
                        .WithMany()
                        .HasForeignKey("DeploymentBindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemoteSSL.Domain.Entities.DeploymentJob", "DeploymentJob")
                        .WithMany("Targets")
                        .HasForeignKey("DeploymentJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeploymentBinding");

                    b.Navigation("DeploymentJob");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentStep", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.DeploymentJobTarget", "DeploymentJobTarget")
                        .WithMany("Steps")
                        .HasForeignKey("DeploymentJobTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeploymentJobTarget");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.MonitorCertificateLink", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.Certificate", "Certificate")
                        .WithMany("MonitorLinks")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemoteSSL.Domain.Entities.MonitorEndpoint", "MonitorEndpoint")
                        .WithMany("CertificateLinks")
                        .HasForeignKey("MonitorEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("MonitorEndpoint");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.MonitorEndpoint", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.CertificateVersion", "InternalObservedVersion")
                        .WithMany()
                        .HasForeignKey("InternalObservedVersionId");

                    b.HasOne("RemoteSSL.Domain.Entities.CertificateVersion", "LastObservedVersion")
                        .WithMany()
                        .HasForeignKey("LastObservedVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InternalObservedVersion");

                    b.Navigation("LastObservedVersion");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.Target", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.CredentialRef", "CredentialRef")
                        .WithMany()
                        .HasForeignKey("CredentialRefId");

                    b.Navigation("CredentialRef");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.Certificate", b =>
                {
                    b.Navigation("MonitorLinks");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateStore", b =>
                {
                    b.Navigation("Bindings");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateVersion", b =>
                {
                    b.Navigation("Sans");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJob", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJobTarget", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.MonitorEndpoint", b =>
                {
                    b.Navigation("CertificateLinks");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.Target", b =>
                {
                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
