// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemoteSSL.Infrastructure.Persistence;

#nullable disable

namespace RemoteSSL.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RemoteSslDbContext))]
    [Migration("20260813110131_DualVantageProbe")]
    partial class DualVantageProbe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RemoteSSL.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DeploymentJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ObjectId")
                        .HasColumnType("text");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CaConnectorConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EncryptedConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("CaConnectors");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Environment")
                        .HasColumnType("text");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<Guid?>("RenewalPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CommonName");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaConnectorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CsrPem")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedPrivateKeyPem")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("IssuedVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("KeyAlgorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyOrigin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeySizeOrCurve")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderRequestId")
                        .HasColumnType("text");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("text");

                    b.Property<string>("SansJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetKeyPath")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("CertificateRequests");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateSan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SanType")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("CertificateVersionId");

                    b.HasIndex("Value");

                    b.ToTable("CertificateSans");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StorePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("StoreType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.ToTable("CertificateStores");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedPrivateKeyPem")
                        .HasColumnType("text");

                    b.Property<string>("IssuerDn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeySize")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PemCertificate")
                        .HasColumnType("text");

                    b.Property<string>("PemChain")
                        .HasColumnType("text");

                    b.Property<string>("PublicKeyAlgorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Sha1Thumbprint")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Sha256Thumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SignatureAlgorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectDn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("NotAfter");

                    b.HasIndex("Sha256Thumbprint")
                        .IsUnique();

                    b.HasIndex("IssuerDn", "SerialNumber");

                    b.ToTable("CertificateVersions");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CredentialRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessPolicyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CredentialType")
                        .HasColumnType("integer");

                    b.Property<string>("EncryptedSecret")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("SecretIdentifier")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CredentialRefs");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationPolicyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateStoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceBindingJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("CertificateStoreId");

                    b.ToTable("DeploymentBindings");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("CertificateVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("StopOnFailure")
                        .HasColumnType("boolean");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CertificateVersionId");

                    b.HasIndex("CorrelationId");

                    b.ToTable("DeploymentJobs");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJobTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeploymentBindingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeploymentJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentBindingId");

                    b.HasIndex("DeploymentJobId");

                    b.ToTable("DeploymentJobTargets");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeploymentJobTargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("SafeLog")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentJobTargetId");

                    b.ToTable("DeploymentSteps");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.MonitorCertificateLink", b =>
                {
                    b.Property<Guid>("MonitorEndpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MonitorEndpointId", "CertificateId");

                    b.HasIndex("CertificateId");

                    b.ToTable("MonitorCertificateLinks");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.MonitorEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExternalProbeEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("InternalChainError")
                        .HasColumnType("text");

                    b.Property<bool?>("InternalChainValid")
                        .HasColumnType("boolean");

                    b.Property<bool?>("InternalHostnameValid")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("InternalObservedVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("InternalProbeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalProbeError")
                        .HasColumnType("text");

                    b.Property<int>("InternalProbeStatus")
                        .HasColumnType("integer");

                    b.Property<string>("InternalTlsProtocol")
                        .HasColumnType("text");

                    b.Property<string>("LastChainError")
                        .HasColumnType("text");

                    b.Property<bool?>("LastChainValid")
                        .HasColumnType("boolean");

                    b.Property<bool?>("LastHostnameValid")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastObservedVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastProbeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastProbeError")
                        .HasColumnType("text");

                    b.Property<int>("LastProbeStatus")
                        .HasColumnType("integer");

                    b.Property<string>("LastTlsProtocol")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int?>("ProbeIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sni")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InternalObservedVersionId");

                    b.HasIndex("LastObservedVersionId");

                    b.HasIndex("Host", "Port", "Sni")
                        .IsUnique();

                    b.ToTable("MonitorEndpoints");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.RenewalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ApprovalRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoDeploy")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CaConnectorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MaintenanceWindowJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text");

                    b.Property<bool>("RotateKey")
                        .HasColumnType("boolean");

                    b.Property<int>("TriggerDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RenewalPolicies");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.RunnerJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeploymentJobTargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "RunnerId");

                    b.ToTable("RunnerJobs");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.RunnerNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .HasColumnType("text");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IdentityCertThumbprint")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Segment")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Runners");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.ServicePath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MonitorIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ServicePaths");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConnectionConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CredentialRefId")
                        .HasColumnType("uuid");

                    b.Property<string>("Environment")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OsType")
                        .HasColumnType("text");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CredentialRefId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateSan", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.CertificateVersion", "CertificateVersion")
                        .WithMany("Sans")
                        .HasForeignKey("CertificateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificateVersion");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateStore", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.Target", "Target")
                        .WithMany("Stores")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateVersion", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.Certificate", "Certificate")
                        .WithMany("Versions")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentBinding", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemoteSSL.Domain.Entities.CertificateStore", "CertificateStore")
                        .WithMany("Bindings")
                        .HasForeignKey("CertificateStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("CertificateStore");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJob", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.CertificateVersion", "CertificateVersion")
                        .WithMany()
                        .HasForeignKey("CertificateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificateVersion");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJobTarget", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.DeploymentBinding", "DeploymentBinding")
                        .WithMany()
                        .HasForeignKey("DeploymentBindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemoteSSL.Domain.Entities.DeploymentJob", "DeploymentJob")
                        .WithMany("Targets")
                        .HasForeignKey("DeploymentJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeploymentBinding");

                    b.Navigation("DeploymentJob");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentStep", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.DeploymentJobTarget", "DeploymentJobTarget")
                        .WithMany("Steps")
                        .HasForeignKey("DeploymentJobTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeploymentJobTarget");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.MonitorCertificateLink", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.Certificate", "Certificate")
                        .WithMany("MonitorLinks")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemoteSSL.Domain.Entities.MonitorEndpoint", "MonitorEndpoint")
                        .WithMany("CertificateLinks")
                        .HasForeignKey("MonitorEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("MonitorEndpoint");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.MonitorEndpoint", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.CertificateVersion", "InternalObservedVersion")
                        .WithMany()
                        .HasForeignKey("InternalObservedVersionId");

                    b.HasOne("RemoteSSL.Domain.Entities.CertificateVersion", "LastObservedVersion")
                        .WithMany()
                        .HasForeignKey("LastObservedVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InternalObservedVersion");

                    b.Navigation("LastObservedVersion");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.Target", b =>
                {
                    b.HasOne("RemoteSSL.Domain.Entities.CredentialRef", "CredentialRef")
                        .WithMany()
                        .HasForeignKey("CredentialRefId");

                    b.Navigation("CredentialRef");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.Certificate", b =>
                {
                    b.Navigation("MonitorLinks");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateStore", b =>
                {
                    b.Navigation("Bindings");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.CertificateVersion", b =>
                {
                    b.Navigation("Sans");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJob", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.DeploymentJobTarget", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.MonitorEndpoint", b =>
                {
                    b.Navigation("CertificateLinks");
                });

            modelBuilder.Entity("RemoteSSL.Domain.Entities.Target", b =>
                {
                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
